## Notes
#  1. Azure Virtual Machine name should be unique within the resource group. So specifying the name and resource group should be fine to delete a VM
- name: Delete all resources
  hosts: localhost
  connection: local
  vars_files:
    - variables.yml

  tasks:
    - name: Delete the Virtual Machine
      azure_rm_virtualmachine:
        name: "{{ vm_name }}"  
        resource_group: "{{ resource_group }}"
        location: "{{ location }}"      
        remove_on_absent:
            - virtual_storage
        state: absent
    
    - name: Delete Virtual Network Interface Card
      azure_rm_networkinterface:
        resource_group: "{{ resource_group }}"
        name: "{{ item.nic }}"
        virtual_network: "{{ vnet_name }}"
        subnet: "{{ item.subnet_name }}"        
        state: absent
      with_items: "{{ zones }}"

    - name: Delete Public IP Address
      azure_rm_publicipaddress:
        name: "{{ item.public_ip }}"
        resource_group: "{{ resource_group }}"
        location: "{{ location }}"        
        state: absent
      with_items: "{{ zones }}"