## Create Resource Group in azure

- name: Create Azure Resource Group
  hosts: localhost
  connection: local
  vars_files:
    - variables.yml

  tasks:
  - name: Create a resource group in Azure
    azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"
        state: present
          
