# Look at infrastructure.md file
# Notes:
#   1. While creating a subnet in the virtual network, if you don't specify a network security group then a new one will be created
#   2. While creating a network security group, the rule names cannot have a space in them.
#   3. While creating a NIC,
#       3.1 disable the option - "create_with_security_group" otherwise a security group will be created per nic
#       3.2 if you do not provide a public ip address name, no public ips will be associated with the nic

- name: Setup networking for simple infrastructure
  hosts: localhost
  connection: local
  vars_files:
    - variables.yml

  tasks:
    - name: Create a Virtual Network in Azure
      azure_rm_virtualnetwork:
        name: "{{ vnet_name }}"
        location: "{{ location }}"
        resource_group: "{{ resource_group }}"
        address_prefixes_cidr: "10.0.0.0/16"
        tags:
          project: vdc-ansible
        state: present

    - name: Create Network Security group
      azure_rm_securitygroup:
        name: "{{ security_group }}"
        location: "{{ location }}"
        resource_group: "{{ resource_group }}"
        rules:
          - name: AllowSSH
            protocol: Tcp
            direction: Inbound
            access: Allow
            destination_port_range: 22
            priority: 1001
          - name: DenyRDP
            protocol: Tcp
            direction: Inbound
            access: Deny
            destination_port_range: 3389
            priority: 1000
        state: present

    - name: Add Subnet to the above VNet
      azure_rm_subnet:
        name: "{{ item.subnet_name }}"
        resource_group: "{{ resource_group }}"
        address_prefix_cidr: "{{ item.address_prefix }}"
        security_group: "{{ security_group }}"
        virtual_network_name: "{{ vnet_name }}"
        state: present
      with_items: "{{ zones }}"

    - name: Create Public IP Address
      azure_rm_publicipaddress:
        name: "{{ item.public_ip }}"
        resource_group: "{{ resource_group }}"
        location: "{{ location }}"
        sku: Basic
        allocation_method: Static
        state: present
      with_items: "{{ zones }}"

    - name: Create Virtual Network Interface Card
      azure_rm_networkinterface:
        name: "{{ item.nic }}"
        resource_group: "{{ resource_group }}"
        create_with_security_group: "no"
        location: "{{ location }}"
        virtual_network: "{{ vnet_name }}"
        subnet_name: "{{ item.subnet_name }}"
        security_group: "{{ security_group }}"
        ip_configurations:
          - name: default
            public_ip_address_name: "{{ item.public_ip }}"
            primary: yes
        state: present
      with_items: "{{ zones }}"

